config/routes.rb
Tournament::Application.routes.draw do

  

  devise_for :users

  get "home/index"

  get "site/home"
  match '/home' =>'site#home'

  get "site/teams"
  resources :teams
  match '/teams' =>'site#teams'

  get "site/tournaments"
  resources :competitions
  match '/tournaments' => 'competitions#index'

  get "site/matches"
  resources :matches
  match '/matches' => 'site#matches'

  get "site/results"
  resources :results
  match '/results' => 'site#results'

  
get "site/spirit"
resources :spirit_scores
match '/spirit'=>'spirit_scores#index'

  root :to => 'home#index'

end

app/models/spirit_score.rb
require 'welcome'
class SpiritScore < ActiveRecord::Base
  attr_accessible :Spirit1, :Spirit2, :Spirit3, :Spirit4, :TeamName

  
end

app/controllers/spirit_scores_controller.rb
class SpiritScoresController < ApplicationController
  # GET /spirit_scores
  # GET /spirit_scores.json
  def index
    @spirit_scores = SpiritScore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spirit_scores }
    end
  end

  # GET /spirit_scores/1
  # GET /spirit_scores/1.json
  def show
    @spirit_score = SpiritScore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spirit_score }
    end
  end

  # GET /spirit_scores/new
  # GET /spirit_scores/new.json
  def new
    @spirit_score = SpiritScore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spirit_score }
    end
  end

  # GET /spirit_scores/1/edit
  def edit
    @spirit_score = SpiritScore.find(params[:id])
  end

  # POST /spirit_scores
  # POST /spirit_scores.json
  def create
    @spirit_score = SpiritScore.new(params[:spirit_score])

    respond_to do |format|
      if @spirit_score.save
        format.html { redirect_to @spirit_score, notice: 'Spirit score was successfully created.' }
        format.json { render json: @spirit_score, status: :created, location: @spirit_score }
      else
        format.html { render action: "new" }
        format.json { render json: @spirit_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spirit_scores/1
  # PUT /spirit_scores/1.json
  def update
    @spirit_score = SpiritScore.find(params[:id])

    respond_to do |format|
      if @spirit_score.update_attributes(params[:spirit_score])
        format.html { redirect_to @spirit_score, notice: 'Spirit score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spirit_score.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # AVERAGE------------------------------------------- 
#  def average
 # @spirit_score = SpiritScore.find(params[:id])
  #respond_to do |format|
#end
  
  
	
	end

  # DELETE /spirit_scores/1
  # DELETE /spirit_scores/1.json
  def destroy
    @spirit_score = SpiritScore.find(params[:id])
    @spirit_score.destroy

    respond_to do |format|
      format.html { redirect_to spirit_scores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/spirit_scores_helper.rb
module SpiritScoresHelper
end

app/views/spirit_scores/_form.html.erb
<%= form_for(@spirit_score) do |f| %>
  <% if @spirit_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spirit_score.errors.count, "error") %> prohibited this spirit_score from being saved:</h2>

      <ul>
      <% @spirit_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :TeamName %><br />
    <%= f.text_field :TeamName %>
  </div>
  <div class="field">
    <%= f.label :Spirit1 %><br />
    <%= f.text_field :Spirit1 %>
  </div>
  <div class="field">
    <%= f.label :Spirit2 %><br />
    <%= f.text_field :Spirit2 %>
  </div>
  <div class="field">
    <%= f.label :Spirit3 %><br />
    <%= f.text_field :Spirit3 %>
  </div>
  <div class="field">
    <%= f.label :Spirit4 %><br />
    <%= f.text_field :Spirit4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spirit_scores/edit.html.erb
<h1>Editing spirit_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @spirit_score %> |
<%= link_to 'Back', spirit_scores_path %>

app/views/spirit_scores/index.html.erb
<h1>Listing Spirit Scores</h1>

<table>
  <tr>
    <th>Teamname    |</th>
    <th>Spirit1     |</th>
    <th>Spirit2     |</th>
    <th>Spirit3     |</th>
    <th>Spirit4     |</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spirit_scores.each do |spirit_score| %>
  <tr>
    <td><%= spirit_score.TeamName %></td>
    <td><%= spirit_score.Spirit1 %></td>
    <td><%= spirit_score.Spirit2 %></td>
    <td><%= spirit_score.Spirit3 %></td>
    <td><%= spirit_score.Spirit4 %></td>
    <td><%= link_to 'Edit', edit_spirit_score_path(spirit_score) %></td>
    <td><%= link_to 'Destroy', spirit_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spirit score', new_spirit_score_path %>

app/views/spirit_scores/new.html.erb
<h1>New Spirit Score</h1>

<%= render 'form' %>

<%= link_to 'Back', spirit_scores_path %>

app/views/spirit_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Teamname:</b>
  <%= @spirit_score.TeamName %>
</p>

<p>
  <b>Spirit1:</b>
  <%= @spirit_score.Spirit1 %>
</p>

<p>
  <b>Spirit2:</b>
  <%= @spirit_score.Spirit2 %>
</p>

<p>
  <b>Spirit3:</b>
  <%= @spirit_score.Spirit3 %>
</p>

<p>
  <b>Spirit4:</b>
  <%= @spirit_score.Spirit4 %>
</p>


<%= link_to 'Edit', edit_spirit_score_path(@spirit_score) %> |
<%= link_to 'Back', spirit_scores_path %>

app/views/spirit_scores/spirit.html.erb
<h1> Enter in the spirit scores</h1>

<%= form_tag"/validate" do %>
<%= text_field_tag :search_string %>
<%= submit_tag "Search" %>
<% end %>